# -*- coding: utf-8 -*-
"""IE7374_Project_Model_Training_and_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-wBjJQMHStgE61FD6n_sXRvsoxscAfC

<a href="https://colab.research.google.com/github/jasonhops/IE7374/blob/main/IE7374_Project_Model_Training_and_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#AI Refridgerator Project by Group 12
##Milestone 3: Model Pipeline Implementation
"""

from google.colab import drive
drive.mount('/content/drive')

import gdown
file_id = "13BJXv4_D-7eOGBLKZFjmNL0A-yFPKiHQ"
gdown.download(f"https://drive.google.com/uc?id={file_id}", output="RecipeNLG_dataset.csv", quiet=False)

import pandas as pd

df = pd.read_csv("RecipeNLG_dataset.csv")
df.head()

import json

df["ingredients"] = df["ingredients"].apply(json.loads)
df["directions"] = df["directions"].apply(json.loads)

# Define common fridge items
dairy_items = {
    "milk", "cheese", "butter", "yogurt", "cream", "ghee", "curd", "kefir", "paneer", "ricotta",
    "parmesan", "mozzarella", "custard", "evaporatedmilk", "condensedmilk", "sourcream"
}
protein_items = {
    "egg", "bacon", "ham", "chicken", "turkey", "beef", "pork", "salmon", "tuna", "shrimp",
    "lamb", "duck", "steak", "sausage", "anchovy", "crab", "lobster", "mutton", "tilapia", "venison"
}
vegetable_items = {
    "lettuce", "spinach", "kale", "cabbage", "carrot", "onion", "garlic", "tomato", "pepper",
    "zucchini", "cucumber", "broccoli", "cauliflower", "celery", "radish", "turnip", "beet",
    "asparagus", "eggplant", "leek", "okra", "arugula", "parsley", "cilantro", "basil",
    "dill", "chard", "shallot", "scallion", "endive"
}
fungi_items = {
    "mushroom", "shiitake", "portobello", "enoki", "oyster", "cremini"
}
fruit_items = {
    "apple", "grape", "orange", "lemon", "lime", "pear", "peach", "banana", "mango", "blueberry",
    "strawberry", "raspberry", "blackberry", "plum", "apricot", "fig", "date", "melon", "kiwi", "pineapple"
}
grain_items = {
    "rice", "pasta", "noodle", "bread", "quinoa", "couscous", "oats", "barley", "flour", "tortilla",
    "corn", "bun", "bagel", "roll", "biscuit", "cracker", "crouton"
}
condiment_items = {
    "ketchup", "mustard", "mayonnaise", "relish", "vinegar", "sriracha", "pesto", "soy", "tamari",
    "miso", "salsa", "hummus", "tahini", "chutney", "aioli", "dressing", "gravy"
}
spice_items = {
    "salt", "pepper", "cumin", "turmeric", "paprika", "cinnamon", "nutmeg", "oregano",
    "thyme", "rosemary", "chili", "cardamom", "clove", "coriander", "sage"
}
nut_items = {
    "almond", "cashew", "walnut", "pecan", "hazelnut", "peanut", "pistachio", "chia", "flax", "sesame", "hemp"
}
beverage_items = {
    "juice", "soda", "cola", "water", "tea", "coffee", "kombucha", "smoothie", "lemonade"
}

fridge_items = (
    dairy_items |
    protein_items |
    vegetable_items |
    fungi_items |
    fruit_items |
    grain_items |
    condiment_items |
    spice_items |
    nut_items |
    beverage_items
)

#temporary shortlist for Milestone 3: Model Pipeline Implementation
fridge_items = {
    "milk", "cheese", "cream cheese", "butter", "yogurt", "sour cream", "egg",
    "tomato", "onion", "lettuce", "spinach", "cabbage", "zucchini", "carrot",
    "garlic", "cucumber", "pepper", "celery", "apple", "grapes", "corn", "mushroom"
}

# Fridge inventory filter
def has_fridge_item(ingredients):
    match_count = sum(item.lower() in fridge_items for item in ingredients)
    return 2 <= len(ingredients) <= 10 and match_count >= 1

# Apply filter
df_subset = df[df["ingredients"].apply(has_fridge_item)]

# Sample 20% for train set
df_train = df_subset.sample(frac=0.8, random_state=42)

# Use drop to remove train rows from full set
df_test = df_subset.drop(df_train.index)

# Convert ingredients and directions back to string
df_train["text"] = df_train.apply(
    lambda x: f"{', '.join(x['ingredients'])} -> {x['title'].strip()}. Instructions: {' '.join(x['directions']).strip()}",
    axis=1
)
df_train = df_train.dropna(subset=["text"])

df_train["text"].to_csv("filtered_recipes_gpt.txt", index=False, header=False)

with open("filtered_recipes_gpt.txt", "r", encoding="utf-8") as f:
    contents = f.read()
    print(contents)
with open("filtered_recipes_gpt.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()
    print("Number of rows:", len(lines))

import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer
from datasets import load_dataset
from torch.utils.data import DataLoader
from tqdm import tqdm

model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained(model_name)
model.resize_token_embeddings(len(tokenizer))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

from transformers import GPT2Tokenizer
import torch
from torch.utils.data import Dataset, DataLoader

# Load tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

model = GPT2LMHeadModel.from_pretrained("gpt2")
model.resize_token_embeddings(len(tokenizer))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Load training data
with open("filtered_recipes_gpt.txt", "r") as f:
    lines = [line.strip() for line in f if line.strip()]

class RecipeDataset(Dataset):
    def __init__(self, texts, tokenizer, max_length=128):
        self.examples = tokenizer(
            texts,
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt"
        )

    def __len__(self):
        return self.examples["input_ids"].shape[0]

    def __getitem__(self, idx):
        return {
            "input_ids": self.examples["input_ids"][idx],
            "attention_mask": self.examples["attention_mask"][idx],
        }

dataset = RecipeDataset(lines, tokenizer)
loader = DataLoader(dataset, batch_size=2, shuffle=True)

import matplotlib.pyplot as plt
from transformers import GPT2LMHeadModel
model = GPT2LMHeadModel.from_pretrained("gpt2")
model.resize_token_embeddings(len(tokenizer))
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
model.train()

epochs = 15
epoch_losses = []
for epoch in range(epochs):
    total_loss = 0
    for batch in tqdm(loader):
        inputs = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        outputs = model(input_ids=inputs, attention_mask=attention_mask, labels=inputs)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    epoch_losses.append(avg_loss)
    print(f"Epoch {epoch+1} - Loss: {total_loss / len(loader)}")

plt.figure(figsize=(8, 4))
plt.plot(range(1, len(epoch_losses) + 1), epoch_losses, marker='o')
plt.title("Training Loss per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

model.save_pretrained("gpt2-recipes-manual")
tokenizer.save_pretrained("gpt2-recipes-manual")
print("Model saved to 'gpt2-recipes-manual'")

!ls -lh gpt2-recipes-manual

import shutil

shutil.make_archive("gpt2-recipes-manual", 'zip', "gpt2-recipes-manual")

from google.colab import files
files.download('gpt2-recipes-manual.zip')

"""**Model Testing**"""

# Testing
def test_model(prompt, max_length=100):
    model.eval()
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    # Generate output
    output = model.generate(
        **inputs,
        max_length=120,
        do_sample=True,
        top_k=50,
        top_p=0.92,
        temperature=0.65,
        repetition_penalty=1.3,
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id
    )

    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    print("Prompt:", prompt)
    print(generated_text[len(prompt):].strip())

prompt = (
    "Ingredients: egg, flour, sugar\n"
    "Recipe Title: "
)

test_model(prompt)

prompt = (
    "Ingredients: egg, flour, sugar\n"
    "Recipe Title: "
)

test_model(prompt)

prompt = "cheese, tomato, lettuce →"
test_model(prompt)

prompt = "Ingredients: egg, flour, sugar → Recipe:"
test_model(prompt)

prompt = "cheese, tomato, lettuce -> "
test_model(prompt)

# "pepper", "celery", "apple", "grapes", "corn"
prompt = "pepper, celery, apple, grapes, corn -> "
test_model(prompt)

test_model("Ingredients: egg, milk, cheese → Recipe:")
test_model("Ingredients: butter, garlic, mushroom → Recipe:")
test_model("Ingredients: tomato, onion, lettuce → Recipe:")
test_model("Ingredients: zucchini, carrot, sour cream → Recipe:")
test_model("Ingredients: apple, grapes, yogurt → Recipe:")
test_model("Ingredients: cabbage, pepper, celery → Recipe:")
test_model("Ingredients: egg, flour, sugar → Recipe:")
test_model("Ingredients: cheese, tomato, lettuce → Recipe:")
test_model("Ingredients: butter, garlic, mushroom → Recipe:")
test_model("Ingredients: tomato, onion, lettuce → Recipe:")

from torch.nn import CrossEntropyLoss
import math
import torch

def calculate_perplexity(model, tokenizer, text):
    model.eval()

    # Tokenize input
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to(model.device)

    with torch.no_grad():
        outputs = model(**inputs, labels=inputs["input_ids"])
        loss = outputs.loss

    return math.exp(loss.item())

prompt = "Ingredients: egg, flour, sugar → Recipe:"

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
output = model.generate(
    **inputs,
    max_length=100,
    do_sample=False,
    pad_token_id=tokenizer.eos_token_id
)

generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print("Prompt:", prompt)
print(generated_text[len(prompt):].strip())

full_text = prompt + " " + generated_text[len(prompt):].strip()
perplexity = calculate_perplexity(model, tokenizer, full_text)
print(f"Perplexity: {perplexity:.2f}")

from torch.nn import CrossEntropyLoss
import math
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

model.eval()

prompt = "Ingredients: egg, flour, sugar → Recipe:"
reference = "Pancake. Instructions: Mix egg, flour, and sugar. Fry until golden."

inputs = tokenizer(prompt, return_tensors="pt").to(device)
output = model.generate(
    **inputs,
    max_length=100,
    do_sample=False,
    pad_token_id=tokenizer.eos_token_id
)
generated = tokenizer.decode(output[0], skip_special_tokens=True)
generated_cont = generated[len(prompt):].strip()

# BLEU score
smoothie = SmoothingFunction().method4
bleu = sentence_bleu([reference.split()], generated_cont.split(), smoothing_function=smoothie)

# Perplexity
def calculate_perplexity(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True).to(model.device)
    with torch.no_grad():
        outputs = model(**inputs, labels=inputs["input_ids"])
        return math.exp(outputs.loss.item())

ppl = calculate_perplexity(prompt + " " + generated_cont)

print("Prompt:", prompt)
print(generated_cont)
print(f"BLEU: {bleu:.3f}")
print(f"Perplexity: {ppl:.2f}")